### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Inferencer** [xg-chu/GPAvatar#2]
I'm using windows annaconda, had a little trouble with the building of resources but I think it's ok, however when running either single image or video i get the same errors

```
(track) C:\Users\Jack\GPAvatar>python inference.py -r ./checkpoints/one_model.ckpt --driver ./demos/drivers/vdriver1 --input ./demos/examples/art1 -v
C:\Users\Jack\anaconda3\envs\track\lib\site-packages\torchaudio\backend\utils.py:74: UserWarning: No audio backend is available.
  warnings.warn("No audio backend is available.")
Namespace(driver='./demos/drivers/vdriver1', input='./demos/examples/art1', resume='./checkpoints/one_model.ckpt', frame_num=150, rotate=0, if_video=True)
TASK:
    MODEL_LIST:                 OneShotAvatar
    BUILD_TIME:                 2023.07.23
MODEL:
    MODEL_NAME:                 OneModel
    ENGINE_NAME:                LightningEngine
CAMERA:
    CAMERA_TYPE:                cubic
DATASET_AUGMENT:
    RESIZE:                     512
    RANGE:                      [0, 1]
    SAMPLE_NUMBER:              2
TRAIN:
    GENERAL:
        MONTE_CARLO:            False
        TRAIN_ITER:             200000
        SHOW_STAT_ITER:         100
        BATCH_SIZE_PER_GPU:     2
        MODEL_DUMP_INTERVAL:    5000
        EXP_STR:                OneModel_VFHQ
        TIME_STR:               Feb01_0116_qhpnt
    OPTIMIZER:
        LR:                     0.0001
    SCHEDULER:
        TYPE:                   MultiStepLR
        DECAY_RATE:             0.2
        DECAY_STEP:             [130000, 160000]
DATASET:
    DATASET_NAME:               VFHQ
    DATASET_LOADER:             MVLightningPoints
    DATASET_PATH:               ./Data/VFHQ/img_lmdb
    RECORDS_PATH:               ./Data/VFHQ/dataset.pkl
    METADATA_PATH:              ./Data/VFHQ/camera.json
    BACKGROUND_VALUE:           0.0
DEVICES:                        [0, 1, 2, 3]
flame_scale:        5.0
focal_length:       12.0
principal_point:    [0.0, 0.0]
libpng warning: iCCP: known incorrect sRGB profile
Read video from ./demos/drivers/vdriver1\obama_1.mp4
Only driving data, no image data.
Total frames: 241
C:\Users\Jack\anaconda3\envs\track\lib\site-packages\torchaudio\backend\utils.py:74: UserWarning: No audio backend is available.
  warnings.warn("No audio backend is available.")
Run with online tracking...
Traceback (most recent call last):
  File "C:\Users\Jack\GPAvatar\inference.py", line 257, in <module>
    test_engine.run_video(args.input, args.frame_num, args.rotate)
  File "C:\Users\Jack\GPAvatar\inference.py", line 122, in run_video
    of_image, f_image, f_shape, frame_key, _ = self.get_input_images(image_path)
  File "C:\Users\Jack\GPAvatar\inference.py", line 91, in get_input_images
    input_images, lightning_results = track_engine.track_images(
  File "C:\Users\Jack\GPAvatar\core\libs\lightning_track\track_images.py", line 30, in track_images
    if images[0].max() > 2.0:
IndexError: list index out of range
```

**Comment by Inferencer** [comment]
Oh nvm I see what went wrong, my file path on the inference line was incorrect
